# Generated by Django 2.0.3 on 2018-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyse_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staticFiles/analyse_image/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('pollution_data', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
