# Generated by Django 2.0.3 on 2018-03-23 23:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_analyse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
