# Generated by Django 2.0.3 on 2018-03-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_chatbot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chatbot',
            new_name='chatbot_save',
        ),
    ]
