# Generated by Django 2.0.3 on 2018-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_chatbot_save_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot_save',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
